version: "2"
exclude_patterns:
  - "./.nyc_output/"
  - "./build/"
  - "./coverage/"
  - "./node_modules/"
  - "./src/migrations/"
  - "./src/seeders/"
  - "./src/config/"
  - "./src/models/index.js/"
  - "./src/app.js/"
  - "./src/utils/emailTemplates/"
  - "./src/test/"
  - "./ui/"